#!/usr/bin/python
#####################################
# Copyright (c) openBrain 2019
# Licensed under LGPL v2
#
# This macro will reset position of all part containers to document origin while keeping the absolute object positions
#
# Version history :
# *0.1 : alpha release, almost no test performed
# *0.2 : some typo improvement + commenting for official PR
#
#####################################

    __Name__ = 'PlacementAbsolufy'
    __Comment__ = 'Reset part containers to global origin while keeping object positions'
    __Author__ = 'openBrain'
    __Version__ = '0.2'
    __Date__ = '2019-06-10'
    __License__ = 'LGPL v2'
    __Web__ = 'https://www.freecadweb.org/wiki/Macro_PlacementAbsolufy'
    __Wiki__ = 'https://www.freecadweb.org/wiki/Macro_PlacementAbsolufy'
    __Icon__ = ''
    __Help__ = 'Run the macro with model active in the GUI'
    __Status__ = 'Alpha'
    __Requires__ = 'FreeCAD >= 0.17'
    __Communication__ = 'https://forum.freecadweb.org/viewtopic.php?f=3&t=36869'
    __Files__ = ''

currState = {} #initialize a dictionary to store current object placements

for obj in App.ActiveDocument.Objects: #going through active document objects
    if "Placement" in obj.PropertiesList: #if object has a Placement property
        currState[obj] = obj.getGlobalPlacement() #store the object pointer with its global placement

App.ActiveDocument.openTransaction("Absolufy") #open a transaction for undo management

for obj, plac in currState.items(): #going through all moveable objects
    if obj.isDerivedFrom("App::Part"): #if object is a part container
        obj.Placement = App.Placement(App.Vector(0,0,0),App.Rotation(0,0,0)) #reset its placement to global document origin
    elif obj.TypeId[:5] == "App::": #if object is another App type (typically an origin axis or plane)
        None #do nothing
    else: #for all other objects
        obj.Placement = plac #replace them at their global (absolute) placement

App.ActiveDocument.commitTransaction() #commit transaction
